package com.test.myself.mapper;

import com.test.myself.domain.AgrtOffsetTask;
import com.test.myself.domain.AgrtOffsetTaskInfo;

import java.util.List;

public interface AgrtOffsetTaskMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agrt_offset_task
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long taskId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agrt_offset_task
     *
     * @mbg.generated
     */
    int insert(AgrtOffsetTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agrt_offset_task
     *
     * @mbg.generated
     */
    AgrtOffsetTask selectByPrimaryKey(Long taskId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agrt_offset_task
     *
     * @mbg.generated
     */
    List<AgrtOffsetTask> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agrt_offset_task
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AgrtOffsetTask record);

    AgrtOffsetTaskInfo selectAgrtOffsetTaskInfoById(Long id);
}