package com.test.myself.domain;

import lombok.Data;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table agrt_instance_signature
 *
 * @mbg.generated do_not_delete_during_merge
 */
@Data
public class AgrtInstanceSignature {
    /**
     * Database Column Remarks:
     *   契约实例签章ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agrt_instance_signature.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   契约实例ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agrt_instance_signature.agrt_instance_id
     *
     * @mbg.generated
     */
    private Long agrtInstanceId;

    /**
     * Database Column Remarks:
     *   客户标记(甲方:A,乙方:B,丙方:C,丁方:D)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agrt_instance_signature.cust_flag
     *
     * @mbg.generated
     */
    private String custFlag;

    /**
     * Database Column Remarks:
     *   客户ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agrt_instance_signature.cust_id
     *
     * @mbg.generated
     */
    private Long custId;

    /**
     * Database Column Remarks:
     *   客户名称(公司名称)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agrt_instance_signature.cust_name
     *
     * @mbg.generated
     */
    private String custName;

    /**
     * Database Column Remarks:
     *   客户CA证书指纹
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agrt_instance_signature.cust_ca_fingerprint
     *
     * @mbg.generated
     */
    private String custCaFingerprint;

    /**
     * Database Column Remarks:
     *   待签署:0,签署中:1,签署完成:2,废弃:3
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agrt_instance_signature.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     * Database Column Remarks:
     *   是否生效(是:1,否:0),生效的标准是客户的CA证书指纹已经保存有效值
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agrt_instance_signature.is_effective
     *
     * @mbg.generated
     */
    private Boolean isEffective;

    /**
     * Database Column Remarks:
     *   签章图像所在的X轴位置(单位:毫米)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agrt_instance_signature.img_position_x
     *
     * @mbg.generated
     */
    private Integer imgPositionX;

    /**
     * Database Column Remarks:
     *   签章图像所在的Y轴位置(单位:毫米)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agrt_instance_signature.img_position_y
     *
     * @mbg.generated
     */
    private Integer imgPositionY;

    /**
     * Database Column Remarks:
     *   签章图像所在的合同页数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agrt_instance_signature.img_in_page
     *
     * @mbg.generated
     */
    private Integer imgInPage;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agrt_instance_signature.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agrt_instance_signature.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * Database Column Remarks:
     *   操作员ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agrt_instance_signature.opt_id
     *
     * @mbg.generated
     */
    private Long optId;

    /**
     * Database Column Remarks:
     *   天威签章用户ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agrt_instance_signature.tw_user_id
     *
     * @mbg.generated
     */
    private String twUserId;

    /**
     * Database Column Remarks:
     *   合同ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agrt_instance_signature.contractId
     *
     * @mbg.generated
     */
    private String contractid;

    /**
     * Database Column Remarks:
     *   合同对应签章人ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agrt_instance_signature.signatureId
     *
     * @mbg.generated
     */
    private String signatureid;
}