package com.test.myself.domain;

import lombok.Data;

import java.util.Date;
import java.util.List;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table agrt_instance
 *
 * @mbg.generated do_not_delete_during_merge
 */
@Data
public class AgrtInstance {
    /**
     * Database Column Remarks:
     *   契约实例ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agrt_instance.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   签约服务器对该实例分配的序列号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agrt_instance.server_inst_sn
     *
     * @mbg.generated
     */
    private String serverInstSn;

    /**
     * Database Column Remarks:
     *   契约模板ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agrt_instance.tmpl_id
     *
     * @mbg.generated
     */
    private Long tmplId;

    /**
     * Database Column Remarks:
     *   契约模板版本
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agrt_instance.tmpl_version
     *
     * @mbg.generated
     */
    private String tmplVersion;

    /**
     * Database Column Remarks:
     *   契约模板名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agrt_instance.tmpl_name
     *
     * @mbg.generated
     */
    private String tmplName;

    /**
     * Database Column Remarks:
     *   契约实例序列号(指协议编号或者合同编号,唯一)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agrt_instance.sn
     *
     * @mbg.generated
     */
    private String sn;

    /**
     * Database Column Remarks:
     *   契约实例名称,具体到XX公司和XX公司的某某协议或合同
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agrt_instance.instance_name
     *
     * @mbg.generated
     */
    private String instanceName;

    /**
     * Database Column Remarks:
     *   需要签章个数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agrt_instance.require_signature_num
     *
     * @mbg.generated
     */
    private Integer requireSignatureNum;

    /**
     * Database Column Remarks:
     *   待签约的客户(结合状态判断,如果不是签署完成或废弃,就代表需要这个字段指定的客户进行签约,需要显示给这个指定的客户查看并签约)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agrt_instance.to_be_signed_cust
     *
     * @mbg.generated
     */
    private Long toBeSignedCust;

    /**
     * Database Column Remarks:
     *   是否启用(启用:1,停用:0)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agrt_instance.is_available
     *
     * @mbg.generated
     */
    private Boolean isAvailable;

    /**
     * Database Column Remarks:
     *   契约实例状态(待签署:0,签署中:1签署完成:2,废弃:3)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agrt_instance.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     * Database Column Remarks:
     *   契约实例文件URL(该值与契约模板文件URL不同,实例文件通过复制模板文件得到,但是有多种状态),理论上不存在该值为空的现象,那意味着合同文件丢失
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agrt_instance.inst_file_url
     *
     * @mbg.generated
     */
    private String instFileUrl;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agrt_instance.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agrt_instance.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * Database Column Remarks:
     *   操作员ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agrt_instance.opt_id
     *
     * @mbg.generated
     */
    private Long optId;

    /**
     * Database Column Remarks:
     *   契约类型 1合同 2补充合同
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agrt_instance.contract_type
     *
     * @mbg.generated
     */
    private Integer contractType;

    /**
     * Database Column Remarks:
     *   OSS文件存放地址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agrt_instance.oss_inst_file_url
     *
     * @mbg.generated
     */
    private String ossInstFileUrl;

    /**
     * Database Column Remarks:
     *   合同实例是否签章
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column agrt_instance.is_sign
     *
     * @mbg.generated
     */
    private Boolean isSign;

    List<AgrtInstanceSignature> agrtInstanceSignatureList;
}